# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ldist_valley.py
# Created on: 2016-06-05 09:19:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
flowdir__2_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\flowdir"
flowacc83 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\flowacc83"
valleys = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\valleys"
vallyonly = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\vallyonly"
Output_direction_raster = ""
smothdem83 = "smothdem83"
distridge = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\distridge"
smothdem83__2_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\smothdem83"
distvallyclip = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\distvallyclip"
distvallwgs = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\distvallwgs"
CM_elev_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\elev.asc"
Extract_ldis1 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\Extract_dist1"
ldist_valley_asc = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\ldist_valley.asc"
GM_elev = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\elev.asc"
Extract_ldis3 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\Extract_dist2"
ldist_valley_asc__3_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\ldist_valley.asc"
DM_elev = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\elev.asc"
Extract_ldis2 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\Extract_dist3"
ldist_valley_asc__2_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\ldist_valley.asc"

# Process: Flow Accumulation
arcpy.gp.FlowAccumulation_sa(flowdir__2_, flowacc83, "", "FLOAT")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("\"%flowacc83%\"  >=   100", valleys)

# Process: Reclassify
arcpy.gp.Reclassify_sa(valleys, "VALUE", "0 NODATA;0 1 1", vallyonly, "DATA")

# Process: Euclidean Distance
arcpy.gp.EucDistance_sa(vallyonly, distridge, "", "28.921983022337", Output_direction_raster)

# Process: Extract by Mask
arcpy.gp.ExtractByMask_sa(distridge, smothdem83__2_, distvallyclip)

# Process: Project Raster
arcpy.ProjectRaster_management(distvallyclip, distvallwgs, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NEAREST", "2.8355922196592E-04 2.8355922196592E-04", "WGS_1984_(ITRF00)_To_NAD_1983", "", "PROJCS['NAD_1983_UTM_Zone_13N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-105.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]")

# Process: extract mask CM
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\elev.asc"
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = "-103.6698019919 29.032009197477 -102.942579769096 29.529231420097"
tempEnvironment2 = arcpy.env.cellSize
arcpy.env.cellSize = "2.77777778000001E-04"
tempEnvironment3 = arcpy.env.mask
arcpy.env.mask = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\elev.asc"
arcpy.gp.ExtractByMask_sa(distvallwgs, CM_elev_, Extract_ldis1)
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1
arcpy.env.cellSize = tempEnvironment2
arcpy.env.mask = tempEnvironment3

# Process: Raster to ASCII
arcpy.RasterToASCII_conversion(Extract_ldis1, ldist_valley_asc)

# Process: extract mask GM
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\elev.asc"
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = "-105.1699300894 31.718225977625 -104.48520786663 32.186559311333"
tempEnvironment2 = arcpy.env.cellSize
arcpy.env.cellSize = "2.77777778000002E-04"
tempEnvironment3 = arcpy.env.mask
arcpy.env.mask = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\elev.asc"
arcpy.gp.ExtractByMask_sa(distvallwgs, GM_elev, Extract_ldis3)
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1
arcpy.env.cellSize = tempEnvironment2
arcpy.env.mask = tempEnvironment3

# Process: Raster to ASCII (2)
arcpy.RasterToASCII_conversion(Extract_ldis3, ldist_valley_asc__3_)

# Process: extract mask DM
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\elev.asc"
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = "-104.57461785062 30.448603245144 -103.671562294342 31.073047690088"
tempEnvironment2 = arcpy.env.cellSize
arcpy.env.cellSize = "2.77777778000002E-04"
tempEnvironment3 = arcpy.env.mask
arcpy.env.mask = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\elev.asc"
arcpy.gp.ExtractByMask_sa(distvallwgs, DM_elev, Extract_ldis2)
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1
arcpy.env.cellSize = tempEnvironment2
arcpy.env.mask = tempEnvironment3

# Process: Raster to ASCII (3)
arcpy.RasterToASCII_conversion(Extract_ldis2, ldist_valley_asc__2_)

