# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MSD.py
# Created on: 2016-06-05 18:08:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
flowaccwgs = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\flowaccwgs"
cm_elev = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\elev.asc"
masked_cm = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\Extract_flow1"
flow_acc_asc = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\flow_acc.asc"
gm_elev = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\elev.asc"
masked_gm = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\Extract_flow2"
flow_acc_asc__3_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\flow_acc.asc"
dm_elev = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\elev.asc"
masked_dm = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\Extract_flow3"
flow_acc_asc__2_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\flow_acc.asc"
elevnad83__6_ = "elevnad83"
elevnad83__8_ = "elevnad83"
elevnad83__10_ = "elevnad83"
elevnad83__12_ = "elevnad83"
elevnad83 = "elevnad83"
zmin7x7 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmin7x7"
zmax7x7 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmax7x7"
v7x7 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\7x7"
elevnad83__11_ = "elevnad83"
zmin11x11 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmin11x11"
zmax11x11 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmax11x11"
v11x11 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\11x11"
elevnad83__9_ = "elevnad83"
zmin15x15 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmin15x15"
zmax15x15 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmax15x15"
v15x15 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\15x15"
elevnad83__7_ = "elevnad83"
zmin21x21 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmin21x21"
zmax21x21 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmax21x21"
v21x21 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\21x21"
elevnad83__2_ = "elevnad83"
zmin27x27 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmin27x27"
zmax27x27 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmax27x27"
v27x27 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\27x27"
elevnad83__5_ = "elevnad83"
zmin13x13 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmin13x13"
zmax13x13 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmax13x13"
v13x13 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\13x13"
elevnad83__4_ = "elevnad83"
zmin9x9 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmin9x9"
zmax9x9 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmax9x9"
v9x9 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\9x9"
elevnad83__3_ = "elevnad83"
zmin5x5 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmin5x5"
zmax5x5 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmax5x5"
v5x5 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\5x5"
zmin3x3 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmin3x3"
zmax3x3 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\zmax3x3"
v3x3 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\3x3"
MSD = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\MSD"
msd_wgs1987 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\msd wgs1987"
elev_asc = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\elev.asc"
msd_CM = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\msd_CM"
msd_asc = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\msd.asc"
elev_asc__2_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\elev.asc"
msd_DM = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\msd_DM"
msd_asc__2_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\msd.asc"
elev_asc__3_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\elev.asc"
msd_GM = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\msd\\msd_GM"
msd_asc__3_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\msd.asc"

# Process: Project Raster
arcpy.ProjectRaster_management("", flowaccwgs, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NEAREST", "2.8355922196592E-04 2.8355922196592E-04", "WGS_1984_(ITRF00)_To_NAD_1983", "", "PROJCS['NAD_1983_UTM_Zone_13N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-105.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]")

# Process: extract mask CM
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\elev.asc"
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = "-103.6698019919 29.032009197477 -102.942579769096 29.529231420097"
tempEnvironment2 = arcpy.env.cellSize
arcpy.env.cellSize = "2.77777778000001E-04"
tempEnvironment3 = arcpy.env.mask
arcpy.env.mask = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\elev.asc"
arcpy.gp.ExtractByMask_sa(flowaccwgs, cm_elev, masked_cm)
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1
arcpy.env.cellSize = tempEnvironment2
arcpy.env.mask = tempEnvironment3

# Process: Raster to ASCII CM
arcpy.RasterToASCII_conversion(masked_cm, flow_acc_asc)

# Process: extract mask GM
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\elev.asc"
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = "-105.1699300894 31.718225977625 -104.48520786663 32.186559311333"
tempEnvironment2 = arcpy.env.cellSize
arcpy.env.cellSize = "2.77777778000002E-04"
tempEnvironment3 = arcpy.env.mask
arcpy.env.mask = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\elev.asc"
arcpy.gp.ExtractByMask_sa(flowaccwgs, gm_elev, masked_gm)
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1
arcpy.env.cellSize = tempEnvironment2
arcpy.env.mask = tempEnvironment3

# Process: Raster to ASCII GM
arcpy.RasterToASCII_conversion(masked_gm, flow_acc_asc__3_)

# Process: extract mask DM
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\elev.asc"
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = "-104.57461785062 30.448603245144 -103.671562294342 31.073047690088"
tempEnvironment2 = arcpy.env.cellSize
arcpy.env.cellSize = "2.77777778000002E-04"
tempEnvironment3 = arcpy.env.mask
arcpy.env.mask = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\elev.asc"
arcpy.gp.ExtractByMask_sa(flowaccwgs, dm_elev, masked_dm)
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1
arcpy.env.cellSize = tempEnvironment2
arcpy.env.mask = tempEnvironment3

# Process: Raster to ASCII DM
arcpy.RasterToASCII_conversion(masked_dm, flow_acc_asc__2_)

# Process: Focal Statistics (5)
arcpy.gp.FocalStatistics_sa(elevnad83, zmin7x7, "Rectangle 7 7 CELL", "MINIMUM", "DATA")

# Process: Focal Statistics (6)
arcpy.gp.FocalStatistics_sa(elevnad83, zmax7x7, "Rectangle 7 7 CELL", "MAXIMUM", "DATA")

# Process: Raster Calculator (9)
arcpy.gp.RasterCalculator_sa("(\"%elevnad83 (12)%\" - \"%zmin7x7%\") / (\"%zmax7x7%\" - \"%zmin7x7%\")", v7x7)

# Process: Focal Statistics (9)
arcpy.gp.FocalStatistics_sa(elevnad83, zmin11x11, "Rectangle 11 11 CELL", "MINIMUM", "DATA")

# Process: Focal Statistics (10)
arcpy.gp.FocalStatistics_sa(elevnad83, zmax11x11, "Rectangle 11 11 CELL", "MAXIMUM", "DATA")

# Process: Raster Calculator (8)
arcpy.gp.RasterCalculator_sa("(\"%elevnad83 (11)%\" - \"%zmin11x11%\") / (\"%zmax11x11%\" - \"%zmin11x11%\")", v11x11)

# Process: Focal Statistics (13)
arcpy.gp.FocalStatistics_sa(elevnad83, zmin15x15, "Rectangle 15 15 CELL", "MINIMUM", "DATA")

# Process: Focal Statistics (14)
arcpy.gp.FocalStatistics_sa(elevnad83, zmax15x15, "Rectangle 15 15 CELL", "MAXIMUM", "DATA")

# Process: Raster Calculator (7)
arcpy.gp.RasterCalculator_sa("(\"%elevnad83 (9)%\" - \"%zmin15x15%\") / (\"%zmax15x15%\" - \"%zmin15x15%\")", v15x15)

# Process: Focal Statistics (15)
arcpy.gp.FocalStatistics_sa(elevnad83, zmin21x21, "Rectangle 21 21 CELL", "MINIMUM", "DATA")

# Process: Focal Statistics (16)
arcpy.gp.FocalStatistics_sa(elevnad83, zmax21x21, "Rectangle 21 21 CELL", "MAXIMUM", "DATA")

# Process: Raster Calculator (6)
arcpy.gp.RasterCalculator_sa("(\"%elevnad83 (7)%\" - \"%zmin21x21%\") / (\"%zmax21x21%\" - \"%zmin21x21%\")", v21x21)

# Process: Focal Statistics (17)
arcpy.gp.FocalStatistics_sa(elevnad83, zmin27x27, "Rectangle 27 27 CELL", "MINIMUM", "DATA")

# Process: Focal Statistics (18)
arcpy.gp.FocalStatistics_sa(elevnad83, zmax27x27, "Rectangle 27 27 CELL", "MAXIMUM", "DATA")

# Process: Raster Calculator (5)
arcpy.gp.RasterCalculator_sa("(\"%elevnad83 (2)%\" - \"%zmin27x27%\") / (\"%zmax27x27%\" - \"%zmin27x27%\")", v27x27)

# Process: Focal Statistics (11)
arcpy.gp.FocalStatistics_sa(elevnad83, zmin13x13, "Rectangle 13 13 CELL", "MINIMUM", "DATA")

# Process: Focal Statistics (12)
arcpy.gp.FocalStatistics_sa(elevnad83, zmax13x13, "Rectangle 13 13 CELL", "MAXIMUM", "DATA")

# Process: Raster Calculator (4)
arcpy.gp.RasterCalculator_sa("(\"%elevnad83 (5)%\" - \"%zmin13x13%\") / (\"%zmax13x13%\" - \"%zmin13x13%\")", v13x13)

# Process: Focal Statistics (7)
arcpy.gp.FocalStatistics_sa(elevnad83, zmin9x9, "Rectangle 9 9 CELL", "MINIMUM", "DATA")

# Process: Focal Statistics (8)
arcpy.gp.FocalStatistics_sa(elevnad83, zmax9x9, "Rectangle 9 9 CELL", "MAXIMUM", "DATA")

# Process: Raster Calculator (3)
arcpy.gp.RasterCalculator_sa("(\"%elevnad83 (4)%\" - \"%zmin9x9%\") / (\"%zmax9x9%\" - \"%zmin9x9%\")", v9x9)

# Process: Focal Statistics (4)
arcpy.gp.FocalStatistics_sa(elevnad83, zmin5x5, "Rectangle 5 5 CELL", "MINIMUM", "DATA")

# Process: Focal Statistics (3)
arcpy.gp.FocalStatistics_sa(elevnad83, zmax5x5, "Rectangle 5 5 CELL", "MAXIMUM", "DATA")

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("(\"%elevnad83 (3)%\" - \"%zmin5x5%\") / (\"%zmax5x5%\" - \"%zmin5x5%\")", v5x5)

# Process: Focal Statistics
arcpy.gp.FocalStatistics_sa(elevnad83, zmin3x3, "Rectangle 3 3 CELL", "MINIMUM", "DATA")

# Process: Focal Statistics (2)
arcpy.gp.FocalStatistics_sa(elevnad83, zmax3x3, "Rectangle 3 3 CELL", "MAXIMUM", "DATA")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(\"%elevnad83%\" - \"%zmin3x3%\") / (\"%zmax3x3%\" - \"%zmin3x3%\")", v3x3)

# Process: Raster Calculator (10)
arcpy.gp.RasterCalculator_sa("\"%7x7%\" + \"%11x11%\" + \"%15x15%\" + \"%21x21%\" + \"%27x27%\" + \"%13x13%\" + \"%9x9%\" + \"%5x5%\" + \"%3x3%\"", MSD)

# Process: Project Raster (2)
arcpy.ProjectRaster_management(MSD, msd_wgs1987, "", "NEAREST", "28.921983022337 28.921983022337", "", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Extract by Mask CM
arcpy.gp.ExtractByMask_sa(msd_wgs1987, elev_asc, msd_CM)

# Process: Raster to ASCII
arcpy.RasterToASCII_conversion(msd_CM, msd_asc)

# Process: Extract by Mask DM
arcpy.gp.ExtractByMask_sa(msd_wgs1987, elev_asc__2_, msd_DM)

# Process: Raster to ASCII (2)
arcpy.RasterToASCII_conversion(msd_DM, msd_asc__2_)

# Process: Extract by Mask GM
arcpy.gp.ExtractByMask_sa(msd_wgs1987, elev_asc__3_, msd_GM)

# Process: Raster to ASCII (3)
arcpy.RasterToASCII_conversion(msd_GM, msd_asc__3_)

