# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# radiation.py
# Created on: 2016-06-05 18:12:12.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
elevnad83 = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\grids\\std_exents\\elevnad83"
elevwgs84 = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\elevwgs84"
elev_asc = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\elev.asc"
maskedcm = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\maskedcm"
radcm = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\radcm"
radiation_asc = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\radiation.asc"
elev_asc__3_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\elev.asc"
maskedgm = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\maskedgm"
radgm = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\radgm"
radiation_asc__3_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\radiation.asc"
elev_asc__2_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\elev.asc"
maskeddm = "C:\\Users\\hmpou\\Documents\\ArcGIS\\Default.gdb\\maskeddm"
raddm = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\smoothed060216\\raddm"
radiation_asc__2_ = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\radiation.asc"
Output_direct_radiation_raster = ""
Output_diffuse_radiation_raster = ""
Output_direct_duration_raster = ""
Output_direct_radiation_raster__2_ = ""
Output_diffuse_radiation_raster__2_ = ""
Output_direct_duration_raster__2_ = ""
Output_direct_radiation_raster__3_ = ""
Output_diffuse_radiation_raster__3_ = ""
Output_direct_duration_raster__3_ = ""

# Process: Project Raster
arcpy.ProjectRaster_management(elevnad83, elevwgs84, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NEAREST", "2.83559221965916E-04 2.83559221965916E-04", "WGS_1984_(ITRF00)_To_NAD_1983", "", "PROJCS['NAD_1983_UTM_Zone_13N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-105.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]")

# Process: extract mask CM
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\elev.asc"
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = "-103.6698019919 29.032009197477 -102.942579769096 29.529231420097"
tempEnvironment2 = arcpy.env.cellSize
arcpy.env.cellSize = "2.77777778000001E-04"
tempEnvironment3 = arcpy.env.mask
arcpy.env.mask = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\CM\\elev.asc"
arcpy.gp.ExtractByMask_sa(elevwgs84, elev_asc, maskedcm)
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1
arcpy.env.cellSize = tempEnvironment2
arcpy.env.mask = tempEnvironment3

# Process: Area Solar Radiation (2)
arcpy.gp.AreaSolarRadiation_sa(maskedcm, radcm, "29.280620308787", "200", "WholeYear   2016", "14", "0.00001036", "NOINTERVAL", "1", "FROM_DEM", "32", "8", "8", "UNIFORM_SKY", "0.3", "0.5", Output_direct_radiation_raster__2_, Output_diffuse_radiation_raster__2_, Output_direct_duration_raster__2_)

# Process: Raster to ASCII
arcpy.RasterToASCII_conversion(radcm, radiation_asc)

# Process: extract mask GM
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\elev.asc"
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = "-105.1699300894 31.718225977625 -104.48520786663 32.186559311333"
tempEnvironment2 = arcpy.env.cellSize
arcpy.env.cellSize = "2.77777778000002E-04"
tempEnvironment3 = arcpy.env.mask
arcpy.env.mask = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\GM\\elev.asc"
arcpy.gp.ExtractByMask_sa(elevwgs84, elev_asc__3_, maskedgm)
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1
arcpy.env.cellSize = tempEnvironment2
arcpy.env.mask = tempEnvironment3

# Process: Area Solar Radiation
arcpy.gp.AreaSolarRadiation_sa(maskedgm, radgm, "31.952392644479", "200", "WholeYear   2016", "14", "1", "NOINTERVAL", "0.00001036", "FROM_DEM", "32", "8", "8", "UNIFORM_SKY", "0.3", "0.5", Output_direct_radiation_raster, Output_diffuse_radiation_raster, Output_direct_duration_raster)

# Process: Raster to ASCII (2)
arcpy.RasterToASCII_conversion(radgm, radiation_asc__3_)

# Process: extract mask DM
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\elev.asc"
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = "-104.57461785062 30.448603245144 -103.671562294342 31.073047690088"
tempEnvironment2 = arcpy.env.cellSize
arcpy.env.cellSize = "2.77777778000002E-04"
tempEnvironment3 = arcpy.env.mask
arcpy.env.mask = "C:\\Users\\hmpou\\Documents\\TXDEM051915\\final_zipped_grids\\DM\\DM\\elev.asc"
arcpy.gp.ExtractByMask_sa(elevwgs84, elev_asc__2_, maskeddm)
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1
arcpy.env.cellSize = tempEnvironment2
arcpy.env.mask = tempEnvironment3

# Process: Area Solar Radiation (3)
arcpy.gp.AreaSolarRadiation_sa(maskeddm, raddm, "30.760825467616", "200", "WholeYear   2016", "14", "0.00001036", "NOINTERVAL", "1", "FROM_DEM", "32", "8", "8", "UNIFORM_SKY", "0.3", "0.5", Output_direct_radiation_raster__3_, Output_diffuse_radiation_raster__3_, Output_direct_duration_raster__3_)

# Process: Raster to ASCII (3)
arcpy.RasterToASCII_conversion(raddm, radiation_asc__2_)

